name: CI/CD for Flask App on Google Cloud Run

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    # Configure Docker to use gcloud as a credential helper
    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/flask-app .

    # Push the Docker image to Google Container Registry
    - name: Push Docker image to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/flask-app

    # Deploy to Google Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy flask-app \
          --image gcr.io/${{ secrets.GCP_PROJECT }}/flask-app \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated
