name: Deploy to Google App Engine with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Google Container Registry
      run: echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-app-name .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-app-name

    - name: Deploy to Google App Engine
      run: |
        gcloud app deploy --image-url=gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-app-name --quiet