name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # Adjust branch as necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out the code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Check /tmp directory permissions
        run: |
          ls -ld /tmp
          touch /tmp/test_file && echo "Write permission check passed" > /tmp/test_file
          
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Authenticate with Google Cloud using the service account key
      - name: Authenticate to Google Cloud
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > "${HOME}/gcp-key.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcp-key.json"
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      # Step 5: Deploy to Google App Engine
      - name: Deploy to App Engine
        run: |
          gcloud app deploy --quiet
